# Generated by Django 2.1.8 on 2019-05-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_ssid', models.IntegerField()),
                ('doctor_first_name', models.CharField(max_length=200)),
                ('doctor_family_name', models.CharField(max_length=200)),
                ('doctor_degree', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_ssid', models.IntegerField()),
                ('patient_first_name', models.CharField(max_length=200)),
                ('patient_second_name', models.CharField(max_length=200)),
                ('patient_family_name', models.CharField(max_length=200)),
                ('patient_birth_date', models.DateTimeField()),
                ('patient_street', models.CharField(max_length=200)),
                ('patient_city', models.CharField(max_length=200)),
                ('patient_country', models.CharField(max_length=200)),
                ('patient_zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('building', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('room', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('attending_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_doctor', to='clinic.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_doctor', to='clinic.Doctor')),
            ],
        ),
    ]
