# Generated by Django 2.1.8 on 2019-05-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
